routes/web.php
<?php

use App\Http\Controllers\RegistrosController;
use App\Http\Controllers\SesionesController;
//use App\Http\Controllers\RevisionesController;
//use App\Http\Controllers\RecepcionesController;
//use App\Http\Controllers\ClientesController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[App\Http\Controllers\HomeController::class,'index'])->name('home')->middleware('auth');

/* Route::get('/equipos',[App\Http\Controllers\EquiposController::class, 'index'])-> name('equipos.index'); */
/*Route::get('/clientes',[App\Http\Controllers\ClientesController::class, 'index'])-> name('clientes.index');*/


/*=================================================*/
/*=============== Rutas de equipos ===============*/
/*=================================================*/
Route::get('equipos/select_recepcion',[App\Http\Controllers\EquiposController::class,'select_equipo_recepcion'])->name('equipos.select_recepcion')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('equipos/update_recepcion/{recepcion}',[App\Http\Controllers\EquiposController::class,'update_equipo_recepcion'])->name('equipos.update_recepcion')->middleware(['logueo','rol:recepcionista,admin']);
/* Route::resource('equipos', EquiposController::class)->middleware(['logueo','rol:admin,recepcionista']);/* Crea todas las rutas del controlador de equipos. Para que funcione descomentar la linea 29 de app\Providers\RouteServiceProvider.php   https://www.youtube.com/watch?v=fb4GfNvEf8M&list=PLpKWS6gp0jd_uZiWmjuqLY7LAMaD8UJhc&index=16*/
Route::get('/equipos/create/',[App\Http\Controllers\EquiposController::class,'create'])->name('equipos.create')->middleware(['logueo','rol:recepcionista,admin']);
Route::post('/equipos/store/',[App\Http\Controllers\EquiposController::class,'store'])->name('equipos.store')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/equipos/index/',[App\Http\Controllers\EquiposController::class,'index'])->name('equipos.index')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::patch('/equipos/update/{equipo}',[App\Http\Controllers\EquiposController::class,'update'])->name('equipos.update')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/equipos/edit/{equipo}',[App\Http\Controllers\EquiposController::class,'edit'])->name('equipos.edit')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/equipos/show/{equipo}',[App\Http\Controllers\EquiposController::class,'show'])->name('equipos.show')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::delete('/equipos/destroy/{equipo}',[App\Http\Controllers\EquiposController::class,'destroy'])->name('equipos.destroy')->middleware(['logueo','rol:recepcionista,admin']);

Route::post('/equipos/storeRecepcion/',[App\Http\Controllers\EquiposController::class,'storeRecepcion'])->name('equipos.storeRecepcion')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/equipos/createRecepcion/',[App\Http\Controllers\EquiposController::class,'createRecepcion'])->name('equipos.createRecepcion')->middleware(['logueo','rol:recepcionista,admin']);

/*=================================================*/
/*=============== Rutas de clientes ===============*/
/*=================================================*/

Route::get('clientes/select_recepcion',[App\Http\Controllers\ClientesController::class,'select_cliente_recepcion'])->name('clientes.select_recepcion')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('clientes/update_recepcion/{recepcion}',[App\Http\Controllers\ClientesController::class,'update_cliente_recepcion'])->name('clientes.update_recepcion')->middleware(['logueo','rol:recepcionista,admin']);
/* Route::resource('clientes', ClientesController::class)->middleware(['logueo','rol:recepcionista,admin']); */
Route::get('/clientes/create/',[App\Http\Controllers\ClientesController::class,'create'])->name('clientes.create')->middleware(['logueo','rol:recepcionista,admin']);
Route::post('/clientes/store/',[App\Http\Controllers\ClientesController::class,'store'])->name('clientes.store')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/clientes/index/',[App\Http\Controllers\ClientesController::class,'index'])->name('clientes.index')->middleware(['logueo','rol:recepcionista,admin']);
Route::patch('/clientes/update/{cliente}',[App\Http\Controllers\ClientesController::class,'update'])->name('clientes.update')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/clientes/edit/{cliente}',[App\Http\Controllers\ClientesController::class,'edit'])->name('clientes.edit')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/clientes/show/{cliente}',[App\Http\Controllers\ClientesController::class,'show'])->name('clientes.show')->middleware(['logueo','rol:recepcionista,admin']);
Route::delete('/clientes/destroy/{cliente}',[App\Http\Controllers\ClientesController::class,'destroy'])->name('clientes.destroy')->middleware(['logueo','rol:recepcionista,admin']);

Route::get('/clientes/createRecepcion/',[App\Http\Controllers\ClientesController::class,'createRecepcion'])->name('clientes.createRecepcion')->middleware(['logueo','rol:recepcionista,admin']);

/*=================================================*/
/*=============== Rutas de recepciones ===============*/
/*=================================================*/

Route::get('/recepciones/informe_final/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'add_informe_final'])->name('recepciones.informe_final')->middleware(['logueo','rol:tecnico,admin']);
Route::get('/recepciones/create/{equipo?}/{cliente?}/',[App\Http\Controllers\RecepcionesController::class,'create'])->name('recepciones.create')->middleware(['logueo','rol:recepcionista,admin']);
Route::post('/recepciones/store/{equipo?}/{cliente?}/',[App\Http\Controllers\RecepcionesController::class,'store'])->name('recepciones.store')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/recepciones/index/',[App\Http\Controllers\RecepcionesController::class,'index'])->name('recepciones.index')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
/* Route::get('/recepciones/index/{buscar?}/{NumOrden?}',[App\Http\Controllers\RecepcionesController::class,'index'])->name('recepciones.index')->middleware(['logueo']); */
Route::patch('/recepciones/update/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'update'])->name('recepciones.update')->middleware(['logueo','rol:recepcionista,admin']);
Route::patch('/recepciones/informe/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'agregarInforme'])->name('recepciones.agregarInforme')->middleware(['logueo','rol:tecnico,admin']);
Route::get('/recepciones/edit/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'edit'])->name('recepciones.edit')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/recepciones/show/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'show'])->name('recepciones.show')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::delete('/recepciones/destroy/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'destroy'])->name('recepciones.destroy')->middleware(['logueo','rol:recepcionista,admin']);

Route::get('/recepciones/generar-pdf-ingreso/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'generarPdfIngreso'])->name('recepciones.generarPdfIngreso')->middleware(['logueo','rol:admin,recepcionista']);
Route::get('/recepciones/generar-pdf-informe/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'generarPdfInforme'])->name('recepciones.generarPdfInforme')->middleware(['logueo','rol:admin,recepcionista']);
/* Route::resource('recepciones', RecepcionesController::class)->middleware(['logueo']);
 */

 /*=================================================*/
/*=============== Rutas de logueo ===============*/
/*=================================================*/

Route::get('/login',[SesionesController::class,'create'])->name('login.index')->middleware('logueado');
Route::post('/login',[SesionesController::class,'store'])->name('login.store');
Route::get('/login/destroy',[SesionesController::class,'destroy'])->name('login.destroy');

/*=================================================*/
/*=============== Rutas de registro de usuarios ===============*/
/*=================================================*/

Route::resource('usuarios', UsuariosController::class)->middleware(['logueo','rol:admin']);
Route::get('/usuarios/{usuario}',[App\Http\Controllers\UsuariosController::class,'show'])->name('usuarios.show')->middleware(['logueo','mi_perfil']);
Route::get('/usuarios/edit/{usuario}',[App\Http\Controllers\UsuariosController::class,'edit'])->name('usuarios.edit')->middleware(['logueo','mi_perfil']);
Route::patch('/usuarios/update/{usuario}',[App\Http\Controllers\UsuariosController::class,'update'])->name('usuarios.update')->middleware(['logueo','mi_perfil']);
/* Route::get('/registro/lista',[RegistrosController::class,'index'])->name('registros.index'); */
/* Route::get('/registro',[RegistrosController::class,'create'])->name('registros.create');
Route::post('/registro',[RegistrosController::class,'store'])->name('registros.store');
Route::patch('/registro/update',[RegistrosController::class,'update'])->name('registros.update');
Route::delete('/registro/{user}',[RegistrosController::class,'destroy'])->name('registros.destroy'); */

/*=================================================*/
/*=============== Rutas de Revisiones ===============*/
/*=================================================*/

resources/views/autenticacion/login.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/app.css">
    <script src="{{ mix('js/app.js') }}" type="text/javascript"></script>
    <title>Logueo</title>
</head>
<body {{-- class="bd-green-500" --}} style="background-color: rgb(232 232 232)">
    <header>
        <h1 class="text-center bg-dark" style="color: rgb(150 150 150)">Gestión de Reparaciones</h1>

    </header>
    <div class="container text-center mt-4 py-2 col-4" style="background-color: #82bbc2">
        <div class="row justify-content-center">
<!--             <div class="col-7 position-relative top-50 ">
                <img width="350" height="350" src="https://www.facet.unt.edu.ar/wp-content/uploads/2022/03/FACET-logo.jpg" class="attachment-1200x1200 size-1200x1200" alt="" decoding="async" loading="lazy">
            </div>
 -->            <div class="col-11 mt-4 pb-3">
                <form class="form-signin" method="POST" action="{{route('login.store')}}">
                    @csrf
                    <h2 class="h6 mb-3 fw-normal"><font style="horizontal-align: inherit;">Por favor, ingrese correo electrónico y contraseña</font></h2>
                    
                    <div class="form-floating">
                        <input  class="form-control" placeholder="nombre@ejemplo.com" type="email" name="email" placeholder="Email" value="{{session()->has('emailA')?session()->get('emailA'):''}}" required><br>
                        <label for="email"><font style="vertical-align: inherit;" class="text-dark"><font style="vertical-align: inherit;" class="text-dark">Dirección de correo electrónico</font></font></label>
                    </div>
                    <div class="form-floating">
                        <input class="form-control" type="password" name="password" placeholder="Contraseña" required placeholder="Clave"><br>
                        {{-- <input type="password" class="form-control" id="floatingPassword" placeholder="Clave"> --}}
                        <label for="floatingPassword"><font style="vertical-align: inherit;" class="text-dark"><font style="vertical-align: inherit;" class="text-dark">Clave</font></font></label>
                    </div>
                    
                    {{-- <div class="checkbox mb-3">
                        <label>
                            <input type="checkbox" value="remember-me"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Acuérdate de mí
                            </font></font></label>
                        </div> --}}
                        <button class="col-4 mb-2 border-dark shadow btn btn btn-secondary bg-secondary bg-gradient" type="submit"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Iniciar sesión</font></font></button>
                        {{-- <p class="mt-5 mb-3 text-muted"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">© 2017–2021</font></font></p> --}}
                        <div><a class="col-5 border-dark shadow btn btn-sm btn-secondary bg-secondary bg-gradient mt-1 " href="{{route('password.request')}}" style="color:white">Restablecer Contraseña</a></div>
                </form>
            </div>
        </div>
    </div>


    {{-- <section class="pb-4">
        <div class="bg-white border rounded-5">
          
          <section class="w-100 px-4 py-5 gradient-custom" style="border-radius: .5rem .5rem 0 0;">
            <style>
              .gradient-custom {
                /* fallback for old browsers */
                background: #6a11cb;
      
                /* Chrome 10-25, Safari 5.1-6 */
                background: -webkit-linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1));
      
                /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
                background: linear-gradient(to right, rgba(106, 17, 203, 1), rgba(37, 117, 252, 1))
              }
            </style>
            <div class="row d-flex justify-content-center">
              <div class="col-12 col-md-8 col-lg-6 col-xl-6">
                <div class="card bg-dark text-white" style="border-radius: 1rem;">
                  <div class="card-body p-5 text-center">
      
                    <div class="mb-md-5 mt-md-4 pb-5">
      
                      <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                      <p class="text-white-50 mb-5">Please enter your login and password!</p>
      
                      <div class="form-outline form-white mb-4">
                        <input type="email" id="typeEmailX" class="form-control form-control-lg">
                        <label class="form-label" for="typeEmailX" style="margin-left: 0px;">Dirección de correo electrónico</label>
                      <div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 40px;"></div><div class="form-notch-trailing"></div></div></div>
      
                      <div class="form-outline form-white mb-4">
                        <input type="password" id="typePasswordX" class="form-control form-control-lg">
                        <label class="form-label" for="typePasswordX" style="margin-left: 0px;">Contraseña</label>
                      <div class="form-notch"><div class="form-notch-leading" style="width: 9px;"></div><div class="form-notch-middle" style="width: 64.8px;"></div><div class="form-notch-trailing"></div></div></div>
      
                      <button class="btn btn-outline-light btn-lg px-5" type="submit">Iniciar Sesión</button>
      
      
                    </div>
      
      
                  </div>
                </div>
              </div>
            </div>
          </section>
          
          
          
          <div class="p-4 text-center border-top mobile-hidden">
            <a class="btn btn-link px-3" data-mdb-toggle="collapse" href="#example6" role="button" aria-expanded="false" aria-controls="example6" data-ripple-color="hsl(0, 0%, 67%)">
              <i class="fas fa-code me-md-2"></i>
              <span class="d-none d-md-inline-block">
                Show code
              </span>
            </a>
            
            
              <a class="btn btn-link px-3 " data-ripple-color="hsl(0, 0%, 67%)">
                <i class="fas fa-file-code me-md-2 pe-none"></i>
                <span class="d-none d-md-inline-block export-to-snippet pe-none">
                  Edit in sandbox
                </span>
              </a>
            
          </div>
          
          
        </div>
      </section> --}}


      @if (session()->has('message'))
      <div class="alert alert-warning alert-dismissible" role="alert">
          <strong>{{ session()->get('message') }}</strong> {{ session('success') }}
      </div>
    @endif
</body>
</html>

resources/views/autenticacion/registro.blade.php
@extends('navegacion')

@section('titulo','Registrar usuario')

@section('contenido')
<section class="m-0-auto  text-center">
            <form method="POST" action="{{route('usuarios.store')}}" class="col-8 mx-auto rounded-3 align-items-center bg-form border border-2 border-dark justify-content-center">
                <legend class="bg-dark" style="color:rgb(150 150 150)">Registrar Usuario</legend>
                @csrf 
                <div class="row mx-auto col-11">
                    <div class="col-6">
                        <label for="nombre" class="form-label">Nombre </label>
                        <input type="text" name="nombre" class="form-control border-dark" value="{{ old('nombre')}}" maxlength="{{config("tam_nombre")}}">
                        {!!$errors->first('nombre','<small>:message</small><br>')!!}<br>
                    </div>
                    <div class="col-6">
                        <label for="apellido" class="form-label">Apellido </label>
                        <input type="text" name="apellido" class="form-control border-dark" value="{{ old('apellido')}}" maxlength="{{config("tam_apellido")}}">
                        {!!$errors->first('apellido','<small>:message</small><br>')!!}<br>
                    </div>
                </div>
                <div class="row mb-0 justify-content-center">
                    <div class="col-6 pt-0 mt-2">
                        <label for="email" class="form-label">Correo Electrónico </label>
                        <input type="text" name="email" class="form-control border-dark" value="{{ old('email')}}" maxlength="{{config("tam_mail")}}">
                        {!!$errors->first('email','<small>:message</small><br>')!!}<br>
                    </div>
                    <div class="col-3 pt-0 pb-2">
                        <fieldset class="border border-dark" style="background-color: #f2f2f2">
                            <legend class="w-auto px-2">Roles</legend><br>
                                <div class="d-inline-flex p-0 bd-highlight form-check form-switch d-inline-flex bd-highlight">
                                    <input class="form-check-input" type="checkbox" name="tecnico">
                                    <label class="form-check-label" for="tecnico">Técnico</label>
                                </div><br>
                                <div class="form-check form-switch d-inline-flex bd-highlight pb-3">
                                    <input class="form-check-input" type="checkbox" name="recepcionista">
                                    <label class="form-check-label" for="recepcionista">Recepcionista</label>
                                </div>
                        </fieldset>
                    </div>
                </div>
                <div class="row mx-auto col-11">
                    <div class="col-6">
                        <label for="password" class="form-label">Contraseña </label>
                        <input type="password" name="password" class="form-control border-dark" maxlength="255">
                        {!!$errors->first('password','<small>:message</small><br>')!!}<br>
                        
                    </div>
                    <div class="col-6">
                        <label for="password_confirm" class="form-label">Confirmar contraseña </label>
                        <input type="password" name="password_confirmar" class="form-control border-dark" maxlength="255">
                        {!!$errors->first('password_confirmar','<small>:message</small><br>')!!}<br>
                    </div>
                </div>
                <div class="row mb-0 justify-content-center mb-2">
                    <div class="col-4 me-4 w-auto p-1 rounded " style="background-color: rgb(232, 240, 247)">
                        <input type="submit" value="Registrar" class="btn btn-outline-success">
                    </div>
                    <div class="col-4 ms-4 w-auto p-1 rounded" style="background-color: rgb(232, 240, 247)">
                        <a class="btn btn-outline-danger" href="{{ route('usuarios.index') }}" role="button">Cancelar</a>
                    </div>
                </div>
            </form>
        </section>
    </div>
</div>


@endsection