routes/web.php
<?php

use App\Http\Controllers\RegistrosController;
use App\Http\Controllers\SesionesController;
//use App\Http\Controllers\RevisionesController;
//use App\Http\Controllers\RecepcionesController;
//use App\Http\Controllers\ClientesController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\DB;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[App\Http\Controllers\HomeController::class,'index'])->name('home')->middleware('auth');

/* Route::get('/equipos',[App\Http\Controllers\EquiposController::class, 'index'])-> name('equipos.index'); */
/*Route::get('/clientes',[App\Http\Controllers\ClientesController::class, 'index'])-> name('clientes.index');*/


/*=================================================*/
/*=============== Rutas de equipos ===============*/
/*=================================================*/
Route::get('equipos/select_recepcion',[App\Http\Controllers\EquiposController::class,'select_equipo_recepcion'])->name('equipos.select_recepcion')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('equipos/update_recepcion/{recepcion}',[App\Http\Controllers\EquiposController::class,'update_equipo_recepcion'])->name('equipos.update_recepcion')->middleware(['logueo','rol:recepcionista,admin']);
/* Route::resource('equipos', EquiposController::class)->middleware(['logueo','rol:admin,recepcionista']);/* Crea todas las rutas del controlador de equipos. Para que funcione descomentar la linea 29 de app\Providers\RouteServiceProvider.php   https://www.youtube.com/watch?v=fb4GfNvEf8M&list=PLpKWS6gp0jd_uZiWmjuqLY7LAMaD8UJhc&index=16*/
Route::get('/equipos/create/',[App\Http\Controllers\EquiposController::class,'create'])->name('equipos.create')->middleware(['logueo','rol:recepcionista,admin']);
Route::post('/equipos/store/',[App\Http\Controllers\EquiposController::class,'store'])->name('equipos.store')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/equipos/index/',[App\Http\Controllers\EquiposController::class,'index'])->name('equipos.index')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::patch('/equipos/update/{equipo}',[App\Http\Controllers\EquiposController::class,'update'])->name('equipos.update')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/equipos/edit/{equipo}',[App\Http\Controllers\EquiposController::class,'edit'])->name('equipos.edit')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/equipos/show/{equipo}',[App\Http\Controllers\EquiposController::class,'show'])->name('equipos.show')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::delete('/equipos/destroy/{equipo}',[App\Http\Controllers\EquiposController::class,'destroy'])->name('equipos.destroy')->middleware(['logueo','rol:recepcionista,admin']);

Route::post('/equipos/storeRecepcion/',[App\Http\Controllers\EquiposController::class,'storeRecepcion'])->name('equipos.storeRecepcion')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/equipos/createRecepcion/',[App\Http\Controllers\EquiposController::class,'createRecepcion'])->name('equipos.createRecepcion')->middleware(['logueo','rol:recepcionista,admin']);

/*=================================================*/
/*=============== Rutas de clientes ===============*/
/*=================================================*/

Route::get('clientes/select_recepcion',[App\Http\Controllers\ClientesController::class,'select_cliente_recepcion'])->name('clientes.select_recepcion')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('clientes/update_recepcion/{recepcion}',[App\Http\Controllers\ClientesController::class,'update_cliente_recepcion'])->name('clientes.update_recepcion')->middleware(['logueo','rol:recepcionista,admin']);
/* Route::resource('clientes', ClientesController::class)->middleware(['logueo','rol:recepcionista,admin']); */
Route::get('/clientes/create/',[App\Http\Controllers\ClientesController::class,'create'])->name('clientes.create')->middleware(['logueo','rol:recepcionista,admin']);
Route::post('/clientes/store/',[App\Http\Controllers\ClientesController::class,'store'])->name('clientes.store')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/clientes/index/',[App\Http\Controllers\ClientesController::class,'index'])->name('clientes.index')->middleware(['logueo','rol:recepcionista,admin']);
Route::patch('/clientes/update/{cliente}',[App\Http\Controllers\ClientesController::class,'update'])->name('clientes.update')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/clientes/edit/{cliente}',[App\Http\Controllers\ClientesController::class,'edit'])->name('clientes.edit')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/clientes/show/{cliente}',[App\Http\Controllers\ClientesController::class,'show'])->name('clientes.show')->middleware(['logueo','rol:recepcionista,admin']);
Route::delete('/clientes/destroy/{cliente}',[App\Http\Controllers\ClientesController::class,'destroy'])->name('clientes.destroy')->middleware(['logueo','rol:recepcionista,admin']);

Route::get('/clientes/createRecepcion/',[App\Http\Controllers\ClientesController::class,'createRecepcion'])->name('clientes.createRecepcion')->middleware(['logueo','rol:recepcionista,admin']);

/*=================================================*/
/*=============== Rutas de recepciones ===============*/
/*=================================================*/

Route::get('/recepciones/informe_final/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'add_informe_final'])->name('recepciones.informe_final')->middleware(['logueo','rol:tecnico,admin']);
Route::get('/recepciones/create/{equipo?}/{cliente?}/',[App\Http\Controllers\RecepcionesController::class,'create'])->name('recepciones.create')->middleware(['logueo','rol:recepcionista,admin']);
Route::post('/recepciones/store/{equipo?}/{cliente?}/',[App\Http\Controllers\RecepcionesController::class,'store'])->name('recepciones.store')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/recepciones/index/',[App\Http\Controllers\RecepcionesController::class,'index'])->name('recepciones.index')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
/* Route::get('/recepciones/index/{buscar?}/{NumOrden?}',[App\Http\Controllers\RecepcionesController::class,'index'])->name('recepciones.index')->middleware(['logueo']); */
Route::patch('/recepciones/update/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'update'])->name('recepciones.update')->middleware(['logueo','rol:recepcionista,admin']);
Route::patch('/recepciones/informe/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'agregarInforme'])->name('recepciones.agregarInforme')->middleware(['logueo','rol:tecnico,admin']);
Route::get('/recepciones/edit/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'edit'])->name('recepciones.edit')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/recepciones/show/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'show'])->name('recepciones.show')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::delete('/recepciones/destroy/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'destroy'])->name('recepciones.destroy')->middleware(['logueo','rol:recepcionista,admin']);

Route::get('/recepciones/generar-pdf-ingreso/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'generarPdfIngreso'])->name('recepciones.generarPdfIngreso')->middleware(['logueo','rol:admin,recepcionista']);
Route::get('/recepciones/generar-pdf-informe/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'generarPdfInforme'])->name('recepciones.generarPdfInforme')->middleware(['logueo','rol:admin,recepcionista']);
/* Route::resource('recepciones', RecepcionesController::class)->middleware(['logueo']);
 */

 /*=================================================*/
/*=============== Rutas de logueo ===============*/
/*=================================================*/

Route::get('/login',[SesionesController::class,'create'])->name('login.index')->middleware('logueado');
Route::post('/login',[SesionesController::class,'store'])->name('login.store');
Route::get('/login/destroy',[SesionesController::class,'destroy'])->name('login.destroy');

/*=================================================*/
/*=============== Rutas de registro de usuarios ===============*/
/*=================================================*/

Route::resource('usuarios', UsuariosController::class)->middleware(['logueo','rol:admin']);
Route::get('/usuarios/{usuario}',[App\Http\Controllers\UsuariosController::class,'show'])->name('usuarios.show')->middleware(['logueo','mi_perfil']);
Route::get('/usuarios/edit/{usuario}',[App\Http\Controllers\UsuariosController::class,'edit'])->name('usuarios.edit')->middleware(['logueo','mi_perfil']);
Route::patch('/usuarios/update/{usuario}',[App\Http\Controllers\UsuariosController::class,'update'])->name('usuarios.update')->middleware(['logueo','mi_perfil']);
/* Route::get('/registro/lista',[RegistrosController::class,'index'])->name('registros.index'); */
/* Route::get('/registro',[RegistrosController::class,'create'])->name('registros.create');
Route::post('/registro',[RegistrosController::class,'store'])->name('registros.store');
Route::patch('/registro/update',[RegistrosController::class,'update'])->name('registros.update');
Route::delete('/registro/{user}',[RegistrosController::class,'destroy'])->name('registros.destroy'); */

/*=================================================*/
/*=============== Rutas de Revisiones ===============*/
/*=================================================*/

resources/views/footer.blade.php
{{-- <div class="container">
    <footer class="navbar navbar-fixed-bottom justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
            <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
            </a>
            <span class="text-muted">© 2021 Company, Inc</span>
        </div>
  
        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
        </ul>
    </footer>
</div> --}}

<div class="container mt-1">
    <footer class="pb-1">
        {{-- <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
        </ul> --}}
        <p class=" mb-1 pt-2 text-center text-dark border-top border-dark">© 2021 Company, Inc</p>
    </footer>
</div>

resources/views/navegacion.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/css/app.css">
    <script src="{{ mix('js/app.js') }}" type="text/javascript"></script>
    <link href="{{ asset('css/MiEstilo.css') }}" rel="stylesheet">
    <title>@yield('titulo')</title>
</head>
<body {{-- class="bd-green-500" --}} style="background-color: rgb(232 232 232)">
    <header>
        <h2 class="text-center m-0 {{-- text-light --}}" style="color: rgb(185, 185, 185);background-color: rgb(10, 10, 10)"><b>Gestión de Reparaciones</b></h2>

        <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark mb-2 p-0">
          <div class="container-fluid">
            {{-- <a class="navbar-brand" href="#">Navbar</a> --}}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                
                <li class="nav-item">
                  <a href="/" class="nav-link {{ setActiva('/') }}">
                    Inicio
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house" viewBox="0 0 16 16">
                      <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L2 8.207V13.5A1.5 1.5 0 0 0 3.5 15h9a1.5 1.5 0 0 0 1.5-1.5V8.207l.646.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5ZM13 7.207V13.5a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5V7.207l5-5 5 5Z"/>
                    </svg>
                  </a>
                </li>
                    
                {{-- =============LINKS DE RECEPCIONES============= --}}
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle {{ setActiva('recepciones.*') }}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Recepciones
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clipboard-data" viewBox="0 0 16 16">
                      <path d="M4 11a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0v-1zm6-4a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0V7zM7 9a1 1 0 0 1 2 0v3a1 1 0 1 1-2 0V9z"/>
                      <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                      <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                    </svg>
                  </a>
                  <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                    <li class="nav-item">
                        <a href="{{route('recepciones.index')}}" class="dropdown-item nav-link">Lista de Recepciones</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('recepciones.create')}}" class="dropdown-item nav-link">Nueva Recepcion</a>
                    </li>
                  </ul>
                </li>
                    
                {{-- =============LINKS DE CLIENTES============= --}}
                @if (auth()->user()->tieneRol(['admin','recepcionista']))
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle {{ setActiva('clientes.*') }}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Clientes
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people-fill" viewBox="0 0 16 16">
                      <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7Zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm-5.784 6A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216ZM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"/>
                    </svg>
                  </a>
                  <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                    <li class="nav-item">
                        <a href="{{route('clientes.index')}}" class="dropdown-item nav-link">Lista de Clientes</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('clientes.create')}}" class="dropdown-item nav-link">Registrar Cliente</a>
                    </li>
                  </ul>
                </li>
                @endif
                
                
                {{-- =============LINKS DE EQUIPOS============= --}}
                @if (auth()->user()->tieneRol(['admin','recepcionista','tecnico']))
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle {{ setActiva('equipos.*') }}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Equipos
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-phone" viewBox="0 0 16 16">
                      <path d="M11 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h6zM5 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H5z"/>
                      <path d="M8 14a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
                    </svg>
                  </a>
                  <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                    <li class="nav-item">
                        <a href="{{route('equipos.index')}}" class="dropdown-item nav-link">Lista de Equipos</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('equipos.create')}}" class="dropdown-item nav-link">Registrar Equipo</a>
                    </li>
                  </ul>
                </li>
                @endif

                {{-- =============LINKS DE USUARIOS============= --}}
                @if (auth()->user()->tieneRol(['admin']))
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle {{ setActiva('usuarios.*') }}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Usuarios
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-workspace" viewBox="0 0 16 16">
                      <path d="M4 16s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H4Zm4-5.95a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"/>
                      <path d="M2 1a2 2 0 0 0-2 2v9.5A1.5 1.5 0 0 0 1.5 14h.653a5.373 5.373 0 0 1 1.066-2H1V3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v9h-2.219c.554.654.89 1.373 1.066 2h.653a1.5 1.5 0 0 0 1.5-1.5V3a2 2 0 0 0-2-2H2Z"/>
                    </svg>
                  </a>
                  <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                    <li class="nav-item ">
                        <a href="{{route('usuarios.index')}}"  class="nav-link {{ setActiva('usuarios.*') }}">Lista de Usuarios</a>
                    </li>
                    <li class="nav-item">
                        <!-- <a href="{{route('usuarios.create')}}" class="dropdown-item nav-link">Registrar usuario</a> -->
                        <a href="{{route('usuarios.create')}}" class="nav-link {{ setActiva('usuarios.*') }}">Registrar usuario</a>
                    </li>
                  </ul>
                </li>
                @endif

                
                {{-- =============LINKS DE LISTA DE PRECIOS============= --}}
                <li class="nav-item">
                    <a href="{{route('marcas.index')}}" class="nav-link {{ setActiva('marcas.*') }}">
                      Lista de precios
                      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-receipt" viewBox="0 0 16 16">
                        <path d="M1.92.506a.5.5 0 0 1 .434.14L3 1.293l.646-.647a.5.5 0 0 1 .708 0L5 1.293l.646-.647a.5.5 0 0 1 .708 0L7 1.293l.646-.647a.5.5 0 0 1 .708 0L9 1.293l.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .801.13l.5 1A.5.5 0 0 1 15 2v12a.5.5 0 0 1-.053.224l-.5 1a.5.5 0 0 1-.8.13L13 14.707l-.646.647a.5.5 0 0 1-.708 0L11 14.707l-.646.647a.5.5 0 0 1-.708 0L9 14.707l-.646.647a.5.5 0 0 1-.708 0L7 14.707l-.646.647a.5.5 0 0 1-.708 0L5 14.707l-.646.647a.5.5 0 0 1-.708 0L3 14.707l-.646.647a.5.5 0 0 1-.801-.13l-.5-1A.5.5 0 0 1 1 14V2a.5.5 0 0 1 .053-.224l.5-1a.5.5 0 0 1 .367-.27zm.217 1.338L2 2.118v11.764l.137.274.51-.51a.5.5 0 0 1 .707 0l.646.647.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.646.646.646-.646a.5.5 0 0 1 .708 0l.509.509.137-.274V2.118l-.137-.274-.51.51a.5.5 0 0 1-.707 0L12 1.707l-.646.647a.5.5 0 0 1-.708 0L10 1.707l-.646.647a.5.5 0 0 1-.708 0L8 1.707l-.646.647a.5.5 0 0 1-.708 0L6 1.707l-.646.647a.5.5 0 0 1-.708 0L4 1.707l-.646.647a.5.5 0 0 1-.708 0l-.509-.51z"/>
                        <path d="M3 4.5a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 1 1 0 1h-6a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm8-6a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 0 1h-1a.5.5 0 0 1-.5-.5z"/>
                      </svg>
                    </a>
                </li>
                
              </ul>
              @if (auth()->check())
              <div class="me-5">
                  <a href="{{route('usuarios.show',auth()->user())}}" class="nav-link link-light">
                    {{auth()->user()->apellido.", ".auth()->user()->nombre/* ." Roles: " */}} {{-- figura quien estaría logueado con su rol/es --}}
                  </a> 
              </div>
              <a href="{{route('login.destroy')}}"  class="nav-link link-light" >Cerrar sesión</a>
              @else
              <a href="{{route('login.index')}}" class="nav-link link-light">Log in</a>
              @endif
            </div>
          </div>
        </nav>



    </header>
    <main style="min-height: 34em;">
      @if (session()->has('message'))
      <div class="alert alert-warning alert-dismissible" role="alert" id="error">
          <strong>{{ session()->get('message') }}</strong> {{ session('success') }}
      </div>
      @endif
      <div class="container-fluid mb-3">
      </div>
      @yield('contenido')
      @if(session('error'))
      <script>
        document.getElementById('error').scrollIntoView();
        </script>
      @endif
    </main>
@extends('footer')
</body>
</html>