routes/web.php
Route::get('/clientes/show/{cliente}',[App\Http\Controllers\ClientesController::class,'show'])->name('clientes.show')->middleware(['logueo','rol:recepcionista,admin']);
Route::delete('/clientes/destroy/{cliente}',[App\Http\Controllers\ClientesController::class,'destroy'])->name('clientes.destroy')->middleware(['logueo','rol:recepcionista,admin']);

Route::get('/clientes/createRecepcion/',[App\Http\Controllers\ClientesController::class,'createRecepcion'])->name('clientes.createRecepcion')->middleware(['logueo','rol:recepcionista,admin']);

/*=================================================*/
/*=============== Rutas de recepciones ===============*/
/*=================================================*/

Route::get('/recepciones/informe_final/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'add_informe_final'])->name('recepciones.informe_final')->middleware(['logueo','rol:tecnico,admin']);
Route::get('/recepciones/create/{equipo?}/{cliente?}/',[App\Http\Controllers\RecepcionesController::class,'create'])->name('recepciones.create')->middleware(['logueo','rol:recepcionista,admin']);
Route::post('/recepciones/store/{equipo?}/{cliente?}/',[App\Http\Controllers\RecepcionesController::class,'store'])->name('recepciones.store')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/recepciones/index/',[App\Http\Controllers\RecepcionesController::class,'index'])->name('recepciones.index')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
/* Route::get('/recepciones/index/{buscar?}/{NumOrden?}',[App\Http\Controllers\RecepcionesController::class,'index'])->name('recepciones.index')->middleware(['logueo']); */
Route::patch('/recepciones/update/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'update'])->name('recepciones.update')->middleware(['logueo','rol:recepcionista,admin']);
Route::patch('/recepciones/informe/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'agregarInforme'])->name('recepciones.agregarInforme')->middleware(['logueo','rol:tecnico,admin']);
Route::get('/recepciones/edit/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'edit'])->name('recepciones.edit')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/recepciones/show/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'show'])->name('recepciones.show')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::delete('/recepciones/destroy/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'destroy'])->name('recepciones.destroy')->middleware(['logueo','rol:recepcionista,admin']);

Route::get('/recepciones/generar-pdf-ingreso/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'generarPdfIngreso'])->name('recepciones.generarPdfIngreso')->middleware(['logueo','rol:admin,recepcionista']);
Route::get('/recepciones/generar-pdf-informe/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'generarPdfInforme'])->name('recepciones.generarPdfInforme')->middleware(['logueo','rol:admin,recepcionista']);
/* Route::resource('recepciones', RecepcionesController::class)->middleware(['logueo']);
 */

 /*=================================================*/
/*=============== Rutas de logueo ===============*/
/*=================================================*/

Route::get('/login',[SesionesController::class,'create'])->name('login.index')->middleware('logueado');
Route::post('/login',[SesionesController::class,'store'])->name('login.store');
Route::get('/login/destroy',[SesionesController::class,'destroy'])->name('login.destroy');

/*=================================================*/
/*=============== Rutas de registro de usuarios ===============*/
/*=================================================*/

Route::resource('usuarios', UsuariosController::class)->middleware(['logueo','rol:admin']);
Route::get('/usuarios/{usuario}',[App\Http\Controllers\UsuariosController::class,'show'])->name('usuarios.show')->middleware(['logueo','mi_perfil']);
Route::get('/usuarios/edit/{usuario}',[App\Http\Controllers\UsuariosController::class,'edit'])->name('usuarios.edit')->middleware(['logueo','mi_perfil']);
Route::patch('/usuarios/update/{usuario}',[App\Http\Controllers\UsuariosController::class,'update'])->name('usuarios.update')->middleware(['logueo','mi_perfil']);
/* Route::get('/registro/lista',[RegistrosController::class,'index'])->name('registros.index'); */
/* Route::get('/registro',[RegistrosController::class,'create'])->name('registros.create');
Route::post('/registro',[RegistrosController::class,'store'])->name('registros.store');
Route::patch('/registro/update',[RegistrosController::class,'update'])->name('registros.update');
Route::delete('/registro/{user}',[RegistrosController::class,'destroy'])->name('registros.destroy'); */

/*=================================================*/
/*=============== Rutas de Revisiones ===============*/
/*=================================================*/

/* Route::resource('revisiones', RevisionesController::class)->middleware(['logueo']); */
Route::get('/revisiones/create/{recepcion}',[App\Http\Controllers\RevisionesController::class,'create'])->name('revisiones.create')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::post('/revisiones/store/{recepcion}/',[App\Http\Controllers\RevisionesController::class,'store'])->name('revisiones.store')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
/* Route::get('/revisiones/index/',[App\Http\Controllers\RevisionesController::class,'index'])->name('revisiones.index')->middleware(['logueo']); */
/* Route::get('/revisiones/index/{buscar?}/{NumOrden?}',[App\Http\Controllers\RevisionesController::class,'index'])->name('revisiones.index')->middleware(['logueo']); */
Route::patch('/revisiones/update/{revision}',[App\Http\Controllers\RevisionesController::class,'update'])->name('revisiones.update')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::get('/revisiones/edit/{revision}',[App\Http\Controllers\RevisionesController::class,'edit'])->name('revisiones.edit')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
/* Route::get('/revisiones/show/{revision}',[App\Http\Controllers\RevisionesController::class,'show'])->name('revisiones.show')->middleware(['logueo']); */
Route::delete('/revisiones/destroy/{revision}',[App\Http\Controllers\RevisionesController::class,'destroy'])->name('revisiones.destroy')->middleware('logueo','rol:recepcionista,admin,tecnico');

/*=================================================*/
/*=============== Rutas de Lista de precios ===============*/
/*=================================================*/

Route::resource('precios', PreciosController::class)->middleware(['logueo','rol:admin']);
Route::get('/precios/create/{caracteristica?}',[App\Http\Controllers\PreciosController::class,'create'])->name('precios.create')->middleware(['logueo','rol:admin']);
Route::post('/precios/store/{caracteristica?}/',[App\Http\Controllers\PreciosController::class,'store'])->name('precios.store')->middleware(['logueo','rol:admin']);
Route::post('/precios/store/{caracteristica?}/',[App\Http\Controllers\PreciosController::class,'store'])->name('precios.store')->middleware(['logueo','rol:admin']);

/*=================================================*/
/*=============== Rutas de Marcas ===============*/
/*=================================================*/

Route::get('/marcas/create/',[App\Http\Controllers\MarcasController::class,'create'])->name('marcas.create')->middleware(['logueo','rol:admin']);
Route::post('/marcas/store/',[App\Http\Controllers\MarcasController::class,'store'])->name('marcas.store')->middleware(['logueo','rol:admin']);
Route::get('/marcas/index/',[App\Http\Controllers\MarcasController::class,'index'])->name('marcas.index')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::patch('/marcas/update/{marca}',[App\Http\Controllers\MarcasController::class,'update'])->name('marcas.update')->middleware(['logueo','rol:admin']);
Route::get('/marcas/edit/{marca}',[App\Http\Controllers\MarcasController::class,'edit'])->name('marcas.edit')->middleware(['logueo','rol:admin']);
Route::get('/marcas/show/{marca}',[App\Http\Controllers\MarcasController::class,'show'])->name('marcas.show')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::delete('/marcas/destroy/{marca}',[App\Http\Controllers\MarcasController::class,'destroy'])->name('marcas.destroy')->middleware(['logueo','rol:admin']);;

/*=================================================*/
/*=============== Rutas de Modelos ===============*/
/*=================================================*/

Route::resource('modelos', ModelosController::class)->middleware(['logueo','rol:admin,recepcionista']);
Route::get('/modelos/create/{marca}',[App\Http\Controllers\ModelosController::class,'create'])->name('modelos.create')->middleware(['logueo','rol:admin']);;
Route::post('/modelos/store/{marca}',[App\Http\Controllers\ModelosController::class,'store'])->name('modelos.store')->middleware(['logueo','rol:admin']);;



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/*======================================================================*/
/* ============== Rutas de recuperacion de contraseña ===================*/
/*=======================================================================*/

Route::get('forgot-password', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request')->middleware(['logueado']);
Route::post('forgot-password', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email')->middleware(['logueado']);
Route::get('reset-password/{token}', [App\Http\Controllers\Auth\ResetPasswordController::class, 'showResetForm'])->name('password.reset')->middleware(['logueado']);

app/Models/Marca.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Marca extends Model
{
    protected $table = 'marcas';
    protected $fillable = ['marca'];
    protected $hidden = ['created_at','updated_at'];
    use HasFactory;

    public function caracteristicas(){
        return $this->hasMany('App\Models\Caracteristica','marca_id');
    }

    public static function listarMarcas($buscar){
        $marcas=Marca::where('marca','like','%'.$buscar.'%')
        ->orderBy('marca', 'asc')
        ->paginate(10);
        return $marcas;
    }

    public static function crearMarca(string $marca,$modelo,$tipo){
        try {
            $marca=Marca::firstOrCreate(['marca'=> ucfirst($marca)]);
            if (isset($modelo) && $modelo!=[]) {
                $caracteristica= new Caracteristica([
                    'marca_id'=> $marca['id'],
                    'modelo'=> ucfirst($modelo)
                ]);
                if (isset($tipo)) {
                    $tipo=Tipo::firstOrCreate(['tipo'=> ucfirst($tipo)]);
                    $caracteristica['tipo_id']=$tipo['id'];
                }
                Caracteristica::firstOrCreate([
                    'modelo'=>ucfirst($caracteristica['modelo']),
                    'marca_id'=> $caracteristica['marca_id'],
                    'tipo_id'=>$caracteristica['tipo_id']
                ]);
            }
        } catch (\Exception $e) {
            throw new \Exception('Se ha producido un error al intentar crear la marca.', 0, $e);
        }
    }
    public function agregarModelo(Caracteristica $nuevaCaracteristica){
        foreach ($this->caracteristicas as $caracteristica) {
            if ($caracteristica->modelo == $nuevaCaracteristica->modelo) {
                return;
            }
        }
        $nuevaCaracteristica->marca_id=$this->id;
    }
}

app/Http/Controllers/MarcasController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Marca;
use App\Models\Tipo;
use App\Models\Caracteristica;
class MarcasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        /* $marcas = Marca::paginate(10); */
        $buscar=$request['buscar'];
        $marcas=Marca::listarMarcas($buscar);

        return view('marcas.index',compact('marcas','buscar'));

        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('marcas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'marca'=>'required|max:'.config('tam_marca'),
            'modelo'=>'max:'.config('tam_modelo'),
            'tipo'=>'max:'.config('tam_tipo'),
        ]);
        try {
            Marca::crearMarca($request['marca'],$request['modelo'],$request['tipo']);
            return redirect()->route('marcas.index');
        } catch (\Exception | \Throwable $e) {
            $mensaje = 'Se ha producido un error al intentar cargar los datos';
            return redirect()->back()->with('message', $mensaje);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $marca = Marca::find($id);
        return view('marcas.show',compact('marca'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $marca=Marca::find($id);
        return view('marcas.edit',compact('marca'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'marca'=>'required|max:'.config('tam_marca'),
        ]);
        try {
            $modificarMarca = Marca::find($id);
            if ($marca = Marca::where('marca',$request['marca'])->first()) {
                foreach ($modificarMarca->caracteristicas as $caracteristica) {
                    $marca->agregarModelo($caracteristica);
                }
                if ($modificarMarca->marca != $marca->marca) {
                    $modificarMarca->delete();
                }
            } else {
                $modificarMarca->marca=$request['marca'];
                $modificarMarca->save();
            }
            return redirect()->route('marcas.index');
        } catch (\Illuminate\Database\QueryException $e) {
            $mensaje = 'Se ha producido un error al intentar cargar los datos';
            return redirect()->back()->with('message', $mensaje);
        }
        /* $nuevaMarca = Marca::firstOrCreate(['marca'=> ucfirst(request('marca'))]);
        return $nuevaMarca;
        if ($nuevaMarca != $marca) {
            // Busca todos los caracteristicas que pertenecen a la marca que se está actualizando
            $caracteristicas = Caracteristica::where('marca_id', $marca->id)->get();

            // Actualiza los caracteristicas para que pertenezcan a la nueva marca
            foreach ($caracteristicas as $caracteristica) {
                $caracteristica->marca_id = $nuevaMarca->id;
                $caracteristica->save();
            }

            // Busca y elimina los caracteristicas duplicados en la marca "samsung"
            $caracteristicasRepetidos = Caracteristica::where('marca_id', $nuevaMarca->id)
                                    ->groupBy('modelo')
                                    ->havingRaw('COUNT(*) > 1')
                                    ->get();
            foreach ($caracteristicasRepetidos as $caracteristica) {
                $caracteristicasAEliminar = Caracteristica::where('marca_id', $nuevaMarca->id)
                                        ->where('modelo', $caracteristica->modelo)
                                        ->where('id', '<>', $caracteristica->id)
                                        ->get();
                foreach ($caracteristicasAEliminar as $caracteristicaAEliminar) {
                    $caracteristicaAEliminar->delete();
                }
            }

            // Elimina la marca original
            $marca->delete();
        } else {
            $marca->marca = $request['marca'];
            $marca->save();
        }

        return redirect()->route('marcas.index', $nuevaMarca); */
    }




    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        
        try {
            $marca = Marca::find($id);
            $marca -> delete();
            return redirect()->route('marcas.index');
        } catch (\Illuminate\Database\QueryException $e) {
            $mensaje = 'Se ha producido un error de integridad en la base de datos: Primero debe eliminar las recepciones en las que se registro este quipo.'/*  . $e->getMessage() */;
            return redirect()->back()->with('message', $mensaje)->with('error', true);
        }
    }
}

resources/views/marcas/create.blade.php
@extends('navegacion')

@section('titulo','Registrar Marca')

@section('contenido')

<section class="m-0-auto  text-center">
    <form method="POST" action="{{route('marcas.store')}}" class="col-5 mx-auto rounded-3 align-items-center bg-form border border-2 border-dark justify-content-center">
        <legend class="bg-dark" style="color:rgb(150 150 150)">Registrar Marca</legend>
        @csrf 
        <div class="row justify-content-center">
            <div class="col-6">
                <label for="marca" class="form-label">Marca: </label>
                <input type="text" class="form-control border-dark" name="marca" value="{{ old('marca')}}" maxlength="{{config("tam_marca")}}">
                {!!$errors->first('marca','<small>:message</small><br>')!!}<br>
            </div>
            {{-- <div class="col-4">
                <label for="modelo" class="form-label">Modelo: </label>
                <input type="text" class="form-control border-dark" name="modelo" value="{{ old('modelo')}}" maxlength="{{config("tam_modelo")}}"><br>
                {!!$errors->first('modelo','<small>:message</small><br>')!!}
            </div>
            <div class="col-4">
                <label for="tipo" class="form-label">Tipo: </label>
                <input type="text" class="form-control border-dark" name="tipo" value="{{ old('tipo')}}" maxlength="{{config("tam_tipo")}}"><br>
                {!!$errors->first('tipo','<small>:message</small><br>')!!}
            </div> --}}
        </div>
        <div class="row mb-0 justify-content-center mb-2">
            <div class="col-4 me-4 w-auto p-1 rounded " style="background-color: rgb(232, 240, 247)">
                <input type="submit" value="Registrar" class="btn btn-outline-success">
            </div>
            <div class="col-4 ms-4 w-auto p-1 rounded" style="background-color: rgb(232, 240, 247)">
                <a class="btn btn-outline-danger" href="{{ route('marcas.index') }}" role="button">Cancelar</a>
            </div>
        </div>
    </form>
</section>
@endsection

resources/views/marcas/show.blade.php
@extends('navegacion')

@section('titulo','Ver Marca')

@section('contenido')
@if (auth()->user()->tieneRol(['admin','recepcionista']))    
<div class="ms-5 ps-5">
    <a href="{{route('modelos.create',$marca)}}" class="btn btn-success btn-sm border-dark">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
        </svg>
        Agregar Modelo
    </a>
</div>
@endif
<div class="d-flex justify-content-center">
    <div class="card d-inline-block mx-auto border-dark" style="margin: 0 auto">
        <div class="card-header h4 text-center bg-dark text-light p-1">
            Marca: {{$marca->marca}}
        </div>
        
        <div class="card-body p-0">
            <table class="table p-0 m-0 w-100 table-responsive table-info table-hover table-striped table-bordered border-2 border-dark shadow rounded">
                <thead>
                    <tr>
                        <th>
                            Modelo
                        </th>
                        <th colspan="4" class="text-center">Acciones</th>
                    </tr>
                </thead>
                @forelse ($marca->caracteristicas as $caracteristica)
                <tr>
                    <td>{{$caracteristica->modelo}}</td>
                    <td class="py-1">
                        <button class="btn btn-info dropdown-toggle btn-sm" type="button" id="dropdownMenuClickableInside" data-bs-toggle="dropdown" data-bs-auto-close="outside" aria-expanded="false">
                            Ver Lista de Precios
                        </button>
                        <div class="position-fixed top-50 start-50 translate-middle dropdown-menu p-1 justify-content-center" aria-labelledby="dropdownMenuClickableInside" style="background-color: rgb(196, 231, 255)">
                            {{-- TABLA DESPLEGABLE DE LISTA DE PRECIOS --}}
                            <h4 class="dropdown-header">Lista de precios de modelo: {{$caracteristica->modelo}}
                                @if (auth()->user()->tieneRol(['admin']))
                                    <a class="btn border-dark btn-success btn-sm ms-4" href="{{route('precios.create',$caracteristica->id)}}">Agregar nueva reparacion</a>
                                @endif
                            </h4>
                            {{-- BOTON DE AGREGAR NUEVO PRECIO DE REPARACION --}}
                            <table class="table table-hover table-striped table-bordered bg-white border-2 border-dark rounded m-0">
                                <tr>
                                    <th>Reparacion</th>
                                    <th>Precio</th>
                                    <th>Plazo</th>
                                    <th>Riesgo</th>
                                    <th colspan="1">Acciones</th>
                                </tr>
                                @forelse ($caracteristica->precios as $precio)
                                <tr>
                                    <td>{{$precio->reparacion}}</td>
                                    <td>${{$precio->precio}}</td>
                                    <td>
                                        @if ($precio->plazo)
                                            {{$precio->plazo}} dias
                                        @endif
                                    </td>
                                    <td>{{$precio->riesgo}}</td>
                                    <td>
                                        <a href="{{route('precios.edit',$precio)}}" class="">
                                            <button type="button" class="btn btn-sm btn-primary">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                                </svg>
                                            </button>   
                                        </a>
                                    </td>
                                    <td>
                                        <form method="POST" action="{{route('precios.destroy',$precio)}}">
                                            @csrf @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('¿Está seguro que desea borrar el precio de esta reparación?')">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                                    <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"></path>
                                                </svg>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="5"><p>No se registraron precios</p></td>
                                </tr>
                                @endforelse
                            </table>
                        </div>
                    </td>
                    @if (auth()->user()->tieneRol(['admin','recepcionista']))
                    <td class="py-1">
                        <a class="btn btn-primary btn-sm" href="{{route('modelos.edit',$caracteristica)}}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                            </svg>
                        </a>
                    </td>
                    @endif
                    @if (auth()->user()->tieneRol(['admin']))

                    {{-- BOTON PARA ELIMINAR MODELO --}}

                    <td class="py-1">
                        <form method="POST" action="{{route('modelos.destroy',$caracteristica)}}">
                            @csrf @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('¿Está seguro que desea borrar el Modelo: {{$caracteristica->modelo}}?')">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                    <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"></path>
                                </svg>
                            </button>
                        </form>
                    </td>
                    @endif
                </tr>
                @empty
                <tr>
                    <td colspan="2" class="text-center">No se registró ningun modelo para esta marca.</td>
                </tr>
                @endforelse
            </table>
        </div>
    </div>
</div>
@forelse ($marca->caracteristicas as $caracteristica)

@empty
@endforelse
@endsection