routes/web.php
Route::get('/clientes/show/{cliente}',[App\Http\Controllers\ClientesController::class,'show'])->name('clientes.show')->middleware(['logueo','rol:recepcionista,admin']);
Route::delete('/clientes/destroy/{cliente}',[App\Http\Controllers\ClientesController::class,'destroy'])->name('clientes.destroy')->middleware(['logueo','rol:recepcionista,admin']);

Route::get('/clientes/createRecepcion/',[App\Http\Controllers\ClientesController::class,'createRecepcion'])->name('clientes.createRecepcion')->middleware(['logueo','rol:recepcionista,admin']);

/*=================================================*/
/*=============== Rutas de recepciones ===============*/
/*=================================================*/

Route::get('/recepciones/informe_final/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'add_informe_final'])->name('recepciones.informe_final')->middleware(['logueo','rol:tecnico,admin']);
Route::get('/recepciones/create/{equipo?}/{cliente?}/',[App\Http\Controllers\RecepcionesController::class,'create'])->name('recepciones.create')->middleware(['logueo','rol:recepcionista,admin']);
Route::post('/recepciones/store/{equipo?}/{cliente?}/',[App\Http\Controllers\RecepcionesController::class,'store'])->name('recepciones.store')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/recepciones/index/',[App\Http\Controllers\RecepcionesController::class,'index'])->name('recepciones.index')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
/* Route::get('/recepciones/index/{buscar?}/{NumOrden?}',[App\Http\Controllers\RecepcionesController::class,'index'])->name('recepciones.index')->middleware(['logueo']); */
Route::patch('/recepciones/update/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'update'])->name('recepciones.update')->middleware(['logueo','rol:recepcionista,admin']);
Route::patch('/recepciones/informe/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'agregarInforme'])->name('recepciones.agregarInforme')->middleware(['logueo','rol:tecnico,admin']);
Route::get('/recepciones/edit/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'edit'])->name('recepciones.edit')->middleware(['logueo','rol:recepcionista,admin']);
Route::get('/recepciones/show/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'show'])->name('recepciones.show')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::delete('/recepciones/destroy/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'destroy'])->name('recepciones.destroy')->middleware(['logueo','rol:recepcionista,admin']);

Route::get('/recepciones/generar-pdf-ingreso/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'generarPdfIngreso'])->name('recepciones.generarPdfIngreso')->middleware(['logueo','rol:admin,recepcionista']);
Route::get('/recepciones/generar-pdf-informe/{recepcion}',[App\Http\Controllers\RecepcionesController::class,'generarPdfInforme'])->name('recepciones.generarPdfInforme')->middleware(['logueo','rol:admin,recepcionista']);
/* Route::resource('recepciones', RecepcionesController::class)->middleware(['logueo']);
 */

 /*=================================================*/
/*=============== Rutas de logueo ===============*/
/*=================================================*/

Route::get('/login',[SesionesController::class,'create'])->name('login.index')->middleware('logueado');
Route::post('/login',[SesionesController::class,'store'])->name('login.store');
Route::get('/login/destroy',[SesionesController::class,'destroy'])->name('login.destroy');

/*=================================================*/
/*=============== Rutas de registro de usuarios ===============*/
/*=================================================*/

Route::resource('usuarios', UsuariosController::class)->middleware(['logueo','rol:admin']);
Route::get('/usuarios/{usuario}',[App\Http\Controllers\UsuariosController::class,'show'])->name('usuarios.show')->middleware(['logueo','mi_perfil']);
Route::get('/usuarios/edit/{usuario}',[App\Http\Controllers\UsuariosController::class,'edit'])->name('usuarios.edit')->middleware(['logueo','mi_perfil']);
Route::patch('/usuarios/update/{usuario}',[App\Http\Controllers\UsuariosController::class,'update'])->name('usuarios.update')->middleware(['logueo','mi_perfil']);
/* Route::get('/registro/lista',[RegistrosController::class,'index'])->name('registros.index'); */
/* Route::get('/registro',[RegistrosController::class,'create'])->name('registros.create');
Route::post('/registro',[RegistrosController::class,'store'])->name('registros.store');
Route::patch('/registro/update',[RegistrosController::class,'update'])->name('registros.update');
Route::delete('/registro/{user}',[RegistrosController::class,'destroy'])->name('registros.destroy'); */

/*=================================================*/
/*=============== Rutas de Revisiones ===============*/
/*=================================================*/

/* Route::resource('revisiones', RevisionesController::class)->middleware(['logueo']); */
Route::get('/revisiones/create/{recepcion}',[App\Http\Controllers\RevisionesController::class,'create'])->name('revisiones.create')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::post('/revisiones/store/{recepcion}/',[App\Http\Controllers\RevisionesController::class,'store'])->name('revisiones.store')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
/* Route::get('/revisiones/index/',[App\Http\Controllers\RevisionesController::class,'index'])->name('revisiones.index')->middleware(['logueo']); */
/* Route::get('/revisiones/index/{buscar?}/{NumOrden?}',[App\Http\Controllers\RevisionesController::class,'index'])->name('revisiones.index')->middleware(['logueo']); */
Route::patch('/revisiones/update/{revision}',[App\Http\Controllers\RevisionesController::class,'update'])->name('revisiones.update')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::get('/revisiones/edit/{revision}',[App\Http\Controllers\RevisionesController::class,'edit'])->name('revisiones.edit')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
/* Route::get('/revisiones/show/{revision}',[App\Http\Controllers\RevisionesController::class,'show'])->name('revisiones.show')->middleware(['logueo']); */
Route::delete('/revisiones/destroy/{revision}',[App\Http\Controllers\RevisionesController::class,'destroy'])->name('revisiones.destroy')->middleware('logueo','rol:recepcionista,admin,tecnico');

/*=================================================*/
/*=============== Rutas de Lista de precios ===============*/
/*=================================================*/

Route::resource('precios', PreciosController::class)->middleware(['logueo','rol:admin']);
Route::get('/precios/create/{caracteristica?}',[App\Http\Controllers\PreciosController::class,'create'])->name('precios.create')->middleware(['logueo','rol:admin']);
Route::post('/precios/store/{caracteristica?}/',[App\Http\Controllers\PreciosController::class,'store'])->name('precios.store')->middleware(['logueo','rol:admin']);
Route::post('/precios/store/{caracteristica?}/',[App\Http\Controllers\PreciosController::class,'store'])->name('precios.store')->middleware(['logueo','rol:admin']);

/*=================================================*/
/*=============== Rutas de Marcas ===============*/
/*=================================================*/

Route::get('/marcas/create/',[App\Http\Controllers\MarcasController::class,'create'])->name('marcas.create')->middleware(['logueo','rol:admin']);
Route::post('/marcas/store/',[App\Http\Controllers\MarcasController::class,'store'])->name('marcas.store')->middleware(['logueo','rol:admin']);
Route::get('/marcas/index/',[App\Http\Controllers\MarcasController::class,'index'])->name('marcas.index')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::patch('/marcas/update/{marca}',[App\Http\Controllers\MarcasController::class,'update'])->name('marcas.update')->middleware(['logueo','rol:admin']);
Route::get('/marcas/edit/{marca}',[App\Http\Controllers\MarcasController::class,'edit'])->name('marcas.edit')->middleware(['logueo','rol:admin']);
Route::get('/marcas/show/{marca}',[App\Http\Controllers\MarcasController::class,'show'])->name('marcas.show')->middleware(['logueo','rol:recepcionista,admin,tecnico']);
Route::delete('/marcas/destroy/{marca}',[App\Http\Controllers\MarcasController::class,'destroy'])->name('marcas.destroy')->middleware(['logueo','rol:admin']);;

/*=================================================*/
/*=============== Rutas de Modelos ===============*/
/*=================================================*/

Route::resource('modelos', ModelosController::class)->middleware(['logueo','rol:admin,recepcionista']);
Route::get('/modelos/create/{marca}',[App\Http\Controllers\ModelosController::class,'create'])->name('modelos.create')->middleware(['logueo','rol:admin']);;
Route::post('/modelos/store/{marca}',[App\Http\Controllers\ModelosController::class,'store'])->name('modelos.store')->middleware(['logueo','rol:admin']);;



Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/*======================================================================*/
/* ============== Rutas de recuperacion de contraseña ===================*/
/*=======================================================================*/

Route::get('forgot-password', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'showLinkRequestForm'])->name('password.request')->middleware(['logueado']);
Route::post('forgot-password', [App\Http\Controllers\Auth\ForgotPasswordController::class, 'sendResetLinkEmail'])->name('password.email')->middleware(['logueado']);
Route::get('reset-password/{token}', [App\Http\Controllers\Auth\ResetPasswordController::class, 'showResetForm'])->name('password.reset')->middleware(['logueado']);

app/Http/Controllers/UsuariosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rules;
use Illuminate\Pagination\Paginator;
use App\Models\Recepcion;
use Illuminate\Support\Facades\DB;

use App\Models\Rol;

class UsuariosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $buscar=$request['buscar'];
        $users=User::listarUsuarios($buscar);
        return view('usuarios.index',compact('users','buscar'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('autenticacion.registro');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $field=request()->validate([
                'nombre'=>'required|max:'.config("tam_nombre"),
                'apellido'=>'required|max:'.config("tam_apellido"),
                'email'=>'required|email|max:'.config("tam_email"),
                'password'=>['required',Rules\password::min(4),'max:255'],
                'password_confirmar'=>'required|same:password|max:255',
            ]);
            $field['nombre']=ucfirst($field['nombre']);
            $field['apellido']=ucfirst($field['apellido']);
            $field['password']=bcrypt($field['password']);
            $user = User::create($field);
            if ($request->tecnico=='on') {
                $rol = Rol::get()->where('rol','=','tecnico');
                $user->roles()->attach($rol);
            }
            if ($request->recepcionista=='on') {
                $rol = Rol::get()->where('rol','=','recepcionista');
                $user->roles()->attach($rol);
            }
            /* Auth::loginUsingId($user->id); */
            return redirect()->route('usuarios.index');
        } catch (\Illuminate\Database\QueryException $e) {
            $mensaje = 'Se ha producido un error al intentar cargar los datos';
            return redirect()->back()->with('message', $mensaje);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        $recepciones = $user->recepciones()->distinct()->paginate(10);
        return view('usuarios.show', compact('user', 'recepciones'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('usuarios.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $user = User::find($id);
            if (!auth()->user()->tieneRol(['admin'])) {
                if ($request->password!='') {
                    request()->validate([
                        'password'=>[Rules\password::min(4),'max:255'],
                    ]);
                    $user->password=bcrypt($request->password);
                    $user->save();
                }
                if (isset($request['nombre']) || isset($request['apellido']) || isset($request['email'])) {
                    return redirect()->route('usuarios.show',$user)->with('message','No tienes permisos para modificar tus datos (solo puedes cambiar tu contraseña).');
                }
                return redirect()->route('usuarios.show',$user);
            }
            request()->validate([
                'nombre'=>'required|max:'.config("tam_nombre"),
                'apellido'=>'required|max:'.config("tam_apellido"),
                'email'=>'required|email|max:'.config("tam_email"),
            ]);
            $user['nombre']=ucfirst(request('nombre'));
            $user['apellido']=ucfirst($request['apellido']);
            $user['email']=$request['email'];
            if ($request->tecnico=='on') {
                if (!($user->esTecnico())) {
                    $rol = Rol::get()->where('rol','=','tecnico');
                    $user->roles()->attach($rol);
                }
            } else {
                $user->roles()->detach(Rol::get()->where('rol','=','tecnico'));
            }
            if ($request->recepcionista=='on' ) {
                if (!($user->esRecepcionista())) {
                    $rol = Rol::get()->where('rol','=','recepcionista');
                    $user->roles()->attach($rol);
                }
            } else {
                $user->roles()->detach(Rol::get()->where('rol','=','recepcionista'));
            }

            if ($request->password!='') {
                request()->validate([
                    'password'=>[Rules\password::min(4),'max:255'],
                ]);
                $user->password=bcrypt($request->password);
            }
            $user->save();
            return redirect()->route('usuarios.show',$user);
        } catch (\Illuminate\Database\QueryException $e) {
            $mensaje = 'Se ha producido un error al intentar cargar los datos';
            return redirect()->back()->with('message', $mensaje);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ($id!=1) {   
            $user = User::find($id);
            $user->delete();
        }
        return redirect()->route('usuarios.index');
    }
}

resources/views/usuarios/edit.blade.php
@extends('navegacion')

@section('titulo','Editar usuario')

@section('contenido')
<section class="m-0-auto  text-center">
    <form method="POST" action="{{route('usuarios.update',$user)}}" class="col-8 mx-auto rounded-3 align-items-center bg-form border border-2 border-dark justify-content-center">
        @csrf @method('PATCH')
        <legend>Editar Usuario</legend>
        <div class="row mx-auto col-11">
            <div class="col-6">
                <label for="nombre" class="form-label">Nombre </label>
                <input type="text" name="nombre" class="form-control border-dark" value="{{ old('nombre',$user->nombre)}}"  {{auth()->user()->tieneRol(['admin'])?'':'disabled'}} maxlength="{{config("tam_nombre")}}">
                {!!$errors->first('nombre','<small>:message</small><br>')!!}<br>
            </div>
            <div class="col-6">
                <label for="apellido" class="form-label">Apellido </label>
                <input type="text" name="apellido" class="form-control border-dark" value="{{ old('apellido',$user->apellido)}}"  {{auth()->user()->tieneRol(['admin'])?'':'disabled'}} maxlength="{{config("tam_apellido")}}">
                {!!$errors->first('apellido','<small>:message</small><br>')!!}<br>
        </div>
        <div class="row mx-auto">
            <div class="col-6">
                <label for="email" class="form-label">Correo Electrónico </label>
                <input type="text" name="email" class="form-control border-dark" value="{{ old('email',$user->email)}}"  {{auth()->user()->tieneRol(['admin'])?'':'disabled'}} maxlength="{{config("tam_mail")}}">
                {!!$errors->first('email','<small>:message</small><br>')!!}<br>
            </div>
            <div class="col-6">
                <label for="password" class="form-label">Nueva Contraseña </label>
                <input type="password" name="password" class="form-control border-dark" maxlength="255">
                {!!$errors->first('password','<small>:message</small><br>')!!}<br>
                
            </div>
        </div>
        <div class="row mb-0 justify-content-center">
            <div class="col-3 pt-4 pb-4">
                <fieldset class="border border-dark " style="background-color: #f2f2f2">
                    <legend class="w-auto px-2">Roles</legend><br>
                        <div class="d-inline-flex p-0 bd-highlight form-check form-switch d-inline-flex bd-highlight">
                            <input class="form-check-input" type="checkbox" name="tecnico" {{($user->esTecnico())?'checked':''}} {{auth()->user()->tieneRol(['admin'])?'':'disabled'}}>
                            <label class="form-check-label" for="tecnico">Técnico</label>
                        </div><br>
                        <div class="form-check form-switch d-inline-flex bd-highlight pb-3">
                            <input class="form-check-input" type="checkbox" name="recepcionista" {{($user->esRecepcionista())?'checked':''}} {{auth()->user()->tieneRol(['admin'])?'':'disabled'}}>
                            <label class="form-check-label" for="recepcionista">Recepcionista</label>
                        </div>
                </fieldset>
            </div>
        </div>
        
        <div class="row mb-0 justify-content-center mb-2">
            <div class="col-4 me-4 w-auto p-1 rounded " style="background-color: rgb(232, 240, 247)">
                <input type="submit" value="Registrar" class="btn btn-outline-success">
            </div>
            <div class="col-4 ms-4 w-auto p-1 rounded" style="background-color: rgb(232, 240, 247)">
                <a class="btn btn-outline-danger" href="{{ route('usuarios.show',$user) }}" role="button">Cancelar</a>
            </div>
        </div>
    </form>
</section>
@endsection

resources/views/usuarios/index.blade.php
@extends('navegacion')

@section('titulo','Lista de usuarios')

@section('contenido')

    <div class="container">
        <div class="row mb-2">
            <div class="col-7">
                <a href="{{route('usuarios.create')}}" class="nav-link}}">
                    <button type="button" class="btn btn-success btn-sm border-dark">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"></path>
                            <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"></path>
                        </svg>
                        Registrar Usuario
                    </button>
                </a>
            </div>
            <div class="ps-4 col-5">
                <form class="ps-4 ms-4">
                    <div class="row justify-content-center">
                        <div class="input-group w-50">
                            <input name="buscar" class="form-control border-dark p-1" type="search" placeholder="Buscar Usuario" aria-label="Search" value="{{$buscar}}">
                            <span class="input-group-text border-dark p-1 px-2" id="basic-addon1">
                                    <button style="border:none;" class="p-0">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"></path>
                                    </svg>
                                </button>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="card d-inline-block mx-auto border-dark" style="margin: 0 auto">
            <div class="card-header h4 text-center bg-dark text-light p-1">
                Usuarios
            </div>
            <div class="card-body p-0">
                <table class="table p-0 m-0 w-100 table-responsive table-info table-hover table-striped table-bordered border-2 border-dark shadow rounded">
                    <thead>
                        <tr class="text-center">
                            <th scope="col">Apellido y Nombre</th>
                            <th scope="col">E-mail</th>
                            <th scope="col">Roles</th>
                            <th colspan="2" scope="col">Accion</th>
                        </tr>
                    </thead>
                    @forelse ($users as $usuario)
                    <tr>
                        <td>{{$usuario->apellido.', '.$usuario->nombre}}</td>
                        <td>{{$usuario->email}}</td>
                        <td>
                            @forelse ($usuario->roles as $rol)
                                {{$rol->rol}}
                            @empty
                                No tiene roles
                            @endforelse
                        </td>
                        <td class="p-1 text-center col-1"><a href="{{route('usuarios.show',$usuario)}}" class="btn btn-sm btn-primary">Ver</a></td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="4">No se encontró ningún usuario.</td>
                    </tr>
                    @endforelse
                </table>
            </div>
        </div>
    </div>
    <div class="d-flex justify-content-center mt-2">
        {{ $users->appends($_GET)->links() }}
    </div>
@endsection

resources/views/usuarios/show.blade.php
@extends('navegacion')

@section('titulo','Ver Usuario')

@section('contenido')
<div class="d-flex justify-content-center">
    <div class="card d-inline-block mx-auto border-dark" style="margin: 0 auto">
        <div class="card-header h4 text-center bg-dark text-light p-1">
            Datos del Usuario
        </div>
        <div class="card-body p-0">
            <table class="table p-0 m-0 w-100 table-responsive table-info table-hover table-striped table-bordered border-2 border-dark shadow rounded">
                <tr>
                    <th>Id</th><th>Apellido y Nombre</th><th>E-mail</th><th>Roles</th>
                    <th colspan="2" class="text-center">Accion</th>
                </tr>
                <tr>
                    <td>{{$user->id}}</td>
                    <td>{{ucfirst($user->apellido).', '.ucfirst($user->nombre)}}</td>
                    <td>{{$user->email}}</td>
                    <td>
                        @forelse ($user->roles as $rol)
                        {{ucfirst($rol->rol)}}
                        @empty
                            No tiene roles
                        @endforelse
                    </td>
                    <td class="text-center">
                        <a href="{{route('usuarios.edit',$user)}}" class="">
                            <button type="button" class="btn btn-sm btn-primary">
                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                                    <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                </svg>
                            </button>
                        </a>
                    </td>
                    <td class="text-center">
                        <form method="POST" action="{{route('usuarios.destroy',$user)}}">
                            @csrf @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('¿Está seguro que desea borrar el usuario: {{$user->apellido.', '.$user->nombre}}?')">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash3-fill" viewBox="0 0 16 16">
                                    <path d="M11 1.5v1h3.5a.5.5 0 0 1 0 1h-.538l-.853 10.66A2 2 0 0 1 11.115 16h-6.23a2 2 0 0 1-1.994-1.84L2.038 3.5H1.5a.5.5 0 0 1 0-1H5v-1A1.5 1.5 0 0 1 6.5 0h3A1.5 1.5 0 0 1 11 1.5Zm-5 0v1h4v-1a.5.5 0 0 0-.5-.5h-3a.5.5 0 0 0-.5.5ZM4.5 5.029l.5 8.5a.5.5 0 1 0 .998-.06l-.5-8.5a.5.5 0 1 0-.998.06Zm6.53-.528a.5.5 0 0 0-.528.47l-.5 8.5a.5.5 0 0 0 .998.058l.5-8.5a.5.5 0 0 0-.47-.528ZM8 4.5a.5.5 0 0 0-.5.5v8.5a.5.5 0 0 0 1 0V5a.5.5 0 0 0-.5-.5Z"></path>
                                </svg>
                            </button>
                        </form>
                    </td>
                </tr>
                
            </table>
        </div>
    </div>
</div>

<h4 class=" pt-4 text-center">Recepciones en las que participó </h4>
<div class="d-flex justify-content-center">
    <div class="card d-inline-block mx-auto border-dark" style="margin: 0 auto">
        <div class="card-body p-0">
            <table class="table p-0 m-0 w-100 table-responsive table-info table-hover table-striped table-bordered border-2 border-dark shadow rounded">
                <tr>
                    <th>Modelo</th><th>Marca</th><th>N° Serie</th><th>Fecha Recepción</th>
                    <th>Falla:</th> <th>Cliente</th><th>Estado</th> <th colspan="2">Accion</th>
                </tr>
                @forelse ($recepciones->unique() as $recepcion)
                <tr>
                    @if (isset($recepcion->equipo))
                        <td>{{$recepcion->equipo->caracteristica->modelo}}</td>
                        <td>{{$recepcion->equipo->caracteristica->marca->marca}}</td>
                        <td>{{$recepcion->equipo->numero_serie}}</td>
                    @else
                        <td colspan="3" class="text-center">Equipo Eliminado.</td>
                    @endif
                    <td>{{$recepcion->fecha_recepcion}}</td>
                    <td>{{$recepcion->falla}}</td>
                    {{-- @if (auth()->user()->tieneRol(['admin','recepcionista'])) --}}
                        @if (isset($recepcion->cliente))
                        <td><a href="{{route('clientes.show',$recepcion->cliente)}}">{{$recepcion->cliente->apellido.', '.$recepcion->cliente->nombre}}</a></td>
                        @else
                        <td class="text-center">Cliente Eliminado.</td>
                        @endif
                    {{-- @endif --}}
                    <td>{{$recepcion->estado->estado}}</td>
                    <td><a href="{{route('recepciones.show',$recepcion)}}">Ver</a></td>
                </tr>
                @empty
                <tr>
                    <td colspan="8" class="text-center">
                        <p>No participó en ninguna recepción</p>
                    </td>
                </tr>
                @endforelse
            </table>
        </div>
    </div>
</div>
<div class="mt-2 d-flex justify-content-center">
    {{ $recepciones->links() }}
</div>
@endsection